### ISSUE TITLE
Create java class

### ISSUE THREAD

**Issue by tharindu40** [tharindu40/Java_Code#12]
- Create a folder as test.
- Create a Java class as Main.java with main method.

**Comment by sotiriszogos** [comment]
Hello, can I work on that?

**Comment by tharindu40** [comment]
@sotiriszogos You can create an issue and then work on it.

**Comment by sotiriszogos** [comment]
@tharindu40 What exactly should I do?

**Comment by tharindu40** [comment]
@sotiriszogos You can create new issues for the calculator class.

**Comment by sotiriszogos** [comment]
@tharindu40 Okay, I could do that, but first I think you have to accept my pull request #17 for the issue #13 for the creation of the Calculator class
