### ISSUE TITLE
Create addition method

### ISSUE THREAD

**Issue by tharindu40** [tharindu40/Java_Code#14]
- Create the addition method for adding two numbers inside the Calculator.java class.

**Comment by NUMS-half** [comment]
Could you please assign this issue to me? I will finish this issue as soon as possible.

**Comment by Yasir761** [comment]
@NUMS-half , I already solve it and I'm making PR

**Comment by Yasir761** [comment]
You can add substract method

**Comment by NUMS-half** [comment]
@Yasir761 OK, I got it.
